# Generated by Django 5.1.5 on 2025-02-01 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilbuild', '0003_alter_contractor_certi'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
