# Generated by Django 5.1.5 on 2025-02-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilbuild', '0004_contractor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='certi',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
