# Generated by Django 5.1.5 on 2025-02-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilbuild', '0005_alter_contractor_certi_alter_contractor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='certi',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
