# Generated by Django 5.1.5 on 2025-02-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilbuild', '0006_alter_contractor_certi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('skills', models.CharField(max_length=100)),
                ('expc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contractor',
            name='certi',
            field=models.ImageField(upload_to=''),
        ),
    ]
