# Generated by Django 5.1.5 on 2025-02-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilbuild', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='certi',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
